### ISSUE TITLE
[RFE] mgr nfs module?

### ISSUE THREAD

**Issue by ser** [canonical/microceph#140]
Would it be possible to add the nfs manager module? I think such a simple NFS service is still in microceph scope.

**Comment by sabaini** [comment]
Hey @ser ,

Agreed that nfs would be in scope for MicroCeph.

The nfs mgr module itself is available and enabled by default:

```
sudo microceph.ceph mgr module ls | grep nfs
nfs                on          
```

Or were you looking for something else?

Cheers,
peter.

**Comment by sabaini** [comment]
As a postscriptum, while the nfs mgr module is present we don't have any ganesha services on board. I wouldn't be averse to integrate more comprehensive NFS support but it's not on our immediate roadmap.

**Comment by UtkarshBhatthere** [comment]
Since the original request is resolved, I am marking this issue as closed. Please feel free to open this issue again if relevant.
