### ISSUE TITLE
Is it possible to add support for using a disk partition or loop device (rather than a whole disk) as an osd

### ISSUE THREAD

**Issue by tomponline** [canonical/microceph#146]
There seems to be some restriction in apparmor that only allows very specific whole disks as osd.

**Comment by tomponline** [comment]
In the LXD tests we took inspiration from your microceph tests (thanks!) and had to do quite a dance to get microceph to allow us to use a loop file:

https://github.com/lxc/lxd/blob/master/.github/workflows/tests.yml#L196-L206

**Comment by sabaini** [comment]
Thanks, yes the loopback device support is on our radar -- snapd support for this is has been merged the other day https://github.com/snapcore/snapd/pull/12728 
Longer term I'd like to have an option where microceph allocates a loopback device itself for more convenience

**Comment by tomponline** [comment]
It would be good to be able to use a real disk partition too, not a loop device.

**Comment by tomponline** [comment]
@sabaini is there any news on this?

The reason we ask is because we are using the ephemeral disks on the github test runners and sometimes they are partitions.

**Comment by simondeziel** [comment]
> The reason we ask is because we are using the ephemeral disks on the github test runners and sometimes they are partitions.

Just to highlight that the problem is that sometimes the ephemeral disk is a partition *on the same disk* as the rootfs.

**Comment by sabaini** [comment]
@tomponline we need snapd perms to access partitions, I've created https://github.com/snapcore/snapd/pull/13150 for this

**Comment by tomponline** [comment]
thanks!

**Comment by pitabwire** [comment]
@sabaini after snapcore/snapd#13150 was merged and snapd released in beta. I see microceph is still unable to access a partition.
I tested with this [ansible role](https://github.com/pitabwire/ansible_role_microceph) and get the error : Permission denied.  

Versions I have are :
microceph:  latest/edge
snapd: latest/beta:      2.61

Is there something else I need to do to get it to use the partition?

**Comment by sabaini** [comment]
@pitabwire we will need to hook up the new perms into the microceph snap

**Comment by pitabwire** [comment]
I also see the snap interface [raw-volume ](https://snapcraft.io/docs/raw-volume-interface) is missing, I have created this small PR hopefully to resolve it

**Comment by itoffshore** [comment]
@tomponline - I worked around [the partition issue here](https://github.com/canonical/microceph/issues/251#issuecomment-1809014963)

**Comment by UtkarshBhatthere** [comment]
@tomponline MicroCeph supports automatically creating file based OSDs. This can be done by providing a loop spec to the `add disk` command.
```
sudo microceph add disk 'loop,4G,3'
```
This will create 3 file based OSDs (of size 4G each) and add them as OSDs.

Also, there is a work around available for using partitions (as mentioned by @itoffshore above).
I am marking this issue as closed, but please feel free to re-open it in case you need to.

**Comment by tomponline** [comment]
@UtkarshBhatthere we are really looking for proper support for adding a disk partition for use with microceph, rather than workarounds or loop devices.

My understanding was this was going to need some relaxing of the rules specified by the apparmor profile, but was going to be possible? Has this now changed?

**Comment by UtkarshBhatthere** [comment]
@tomponline we have an active issue [here](https://github.com/canonical/microceph/issues/251) for tracking support for disk partitions. The conversations in that thread also include workarounds (for users who reach there through searches). Since this issue title also includes loop devices (which is now available) I feel we should only keep #251 open for disk partitions.

**Comment by tomponline** [comment]
OK thanks @UtkarshBhatthere
