### ISSUE TITLE
microceph status times out

### ISSUE THREAD

**Issue by marosg42** [canonical/microceph#157]
I noticed while deploying Sunbeam that `microceph status` times out after 30 seconds and reports an error `Error: Get "http://control.socket/cluster/1.0/cluster": context deadline exceeded`
Sunbeam is using `microceph:edge:rev6`
It times out only on multinode deployment

**Comment by gboutry** [comment]
Hi @marosg42, rev 6 is the charm revision, and not the snap revision!

**Comment by gboutry** [comment]
This looks a lot like an issue we had with sunbeam's implementation of microcluster, there was a deadlock, that once reached, made every requests timeout after 30 seconds (deadlock when fetching quorum peers certificates). This was fixed directly in microcluster: https://github.com/canonical/microcluster/commit/f82e569d2fba4350a16b014091f658c8076d002c

**Comment by UtkarshBhatthere** [comment]
@marosg42 I am marking this issue as closed (the above mentioned microcluster fix was fetched to microceph as well: https://github.com/canonical/microceph/pull/158). Feel free to open this issue again If you encounter this error still.
