### ISSUE TITLE
microceph.daemon: http: TLS handshake error from x.x.x.x:port remote error: tls: bad certificat

### ISSUE THREAD

**Issue by karawitan** [canonical/microceph#187]
Hello,

  while checking the logs of my microceph cluster, I hit the following error message:

```
microceph.daemon[262533]: 2023/08/18 17:05:44 http: TLS handshake error from 192.168.1.103:44194: remote error: tls: bad certificat
```

What is the impact of this ? How to fix it ?

**Comment by UtkarshBhatthere** [comment]
Did you see a bug symptom that correlates with this error print ? FWIW, this could be a transient issue while the cluster is setting up, and it is very difficult to point out impacts and fixes with just a print.

**Comment by UtkarshBhatthere** [comment]
I am marking this issue closed, If you feel there is a real bug, please feel free to reopen this issue with detailed symptoms, used channels (e.g. latest/edge can be fetched from snap info microceph) etc.
