### ISSUE TITLE
create dashboard admin user failed with permission denied

### ISSUE THREAD

**Issue by YiHuangIX** [canonical/microceph#189]
root@microceph-1:/home/ubuntu#  ceph dashboard ac-user-create admin -i password administrator
Can't open input file password: [Errno 13] Permission denied: 'password'
Even with chown 777 password, still same.
workaround: 
1. create separate ceph client machine
2. install ceph-common
3. copy ceph conf to client machine /etc/ceph folder
lxc file pull microceph-1/var/snap/microceph/550/conf/* /etc/ceph 

run create dashboard user cmd again
ceph dashboard ac-user-create admin -i password administrator
{"username": "admin", "password": "$2b$12$vLrZj6ulPyXFL6j3P9OohegHlBLSNn9IK1xVgno5fl9UIs7GkGDt2", "roles": ["administrator"], "name": null, "email": null, "lastUpdate": 1692734842, "enabled": true, "pwdExpirationDate": null, "pwdUpdateRequired": false}

**Comment by UtkarshBhatthere** [comment]
Hello @YiHuangIX, Microceph snap is a confined ceph application. The permissions to access files in $HOMEDIR have been very recently added to MC, hence I would request you to kindly refresh (snap refresh microceph --channel quincy/edge) and retry again. The workaround should not be required anymore.

**Comment by UtkarshBhatthere** [comment]
I am closing this issue, however, if you find that refreshing to edge still does not solve it for you, feel free to reopen this issue and we will check into it.

**Comment by YiHuangIX** [comment]
thank you! I will give a try!
