### ISSUE TITLE
Error adding disk after expanding cluster

### ISSUE THREAD

**Issue by gnuoy** [canonical/microceph#194]
As part of sunbeam deployment the initial microceph cluster consists of one unit. More units are added and then an action on charm-microceph is run to add disks. This in turn calls:

```
 microceph disk add device_id
```

This often fails with the following error:

```
Error: Failed adding new disk: Failed to remove microceph_auto_osd rule: Failed to run: ceph osd crush rule rm microceph_auto_osd: exit status 16 (Error EBUSY: crush rule microceph_auto_osd (0) is in use)
```

**Comment by gnuoy** [comment]
I see that test runs that were hitting this were adding nodes and disks in parallel so maybe a fix is needed in charm-microceph as well

**Comment by sabaini** [comment]
Heya @gnuoy , thanks for bringing this up!
Just to note what we discussed before: there is no expectation that scaling up should be done serially so this is indeed a bug (there's some racing going on there). Currently working on a patch which should make the scaling machinery behave better here.
Thanks again!

**Comment by sabaini** [comment]
Hi @gnuoy , 
in PR #186 (currently released in latest/edge) the automatic crush rule management was revamped which I believe should improve the behaviour here -- I'd be interested in getting your observations if you're able to test this

**Comment by UtkarshBhatthere** [comment]
attached the PR but kept the issue open for future references.

**Comment by sabaini** [comment]
This should be fixed
