### ISSUE TITLE
ubuntu@canonical:~$ sudo microceph cluster bootstrap Error: Post "http://control.socket/cluster/control": context deadline exceeded

### ISSUE THREAD

**Issue by KyleSanderson** [canonical/microceph#219]

**Comment by sabaini** [comment]
Hi @KyleSanderson , this is a relatively generic error that basically says the backend daemon was unreachable.

Do you have steps to reproduce this issue? Which microceph version did you use?

Thanks.

**Comment by KyleSanderson** [comment]
I know - just saying the timeout is clearly too low. Whatever was on snap at this time.

**Comment by sabaini** [comment]
Not against raising the timeout in principle but the timeout is 30s which does not seem unreasonable for a relatively light weight operation. What kind of delay have you been seeing? I wonder what a good value for a timeout would be

**Comment by supanadit** [comment]
![image](https://github.com/canonical/microceph/assets/33617149/29696405-04f8-4c83-b595-fd663982fac9)
I also get the same error

**Comment by supanadit** [comment]
I'm actually follow this guide https://microk8s.io/docs/how-to-ceph.
So the error come up when I run this command: `sudo microceph cluster bootstrap` exactly after run `sudo snap install microceph --channel=latest/edge`

My OS Server is: Ubuntu 22.04.03 LTS

**Comment by KyleSanderson** [comment]
> I'm actually follow this guide https://microk8s.io/docs/how-to-ceph. So the error come up when I run this command: `sudo microceph cluster bootstrap` exactly after run `sudo snap install microceph --channel=latest/edge`
> 
> My OS Server is: Ubuntu 22.04.03 LTS

Are you running this on a raid0 NVMe setup?

**Comment by supanadit** [comment]
My server use regular HDD storage with no RAID Configuration. @KyleSanderson

**Comment by KyleSanderson** [comment]
Oh, that's to be expected then.

**Comment by jeffreychang911** [comment]
@KyleSanderson Hi, Solutions QA saw this in several test runs , after `microceph cluster join`
We do have bcache on spinning disks, but still.
Do you think there's any workaround or setting we could add to eliminate this?

test run : https://solutions.qa.canonical.com/testruns/d7c57bfe-83e2-4583-a3cc-b66cdfa2a377
logs : https://oil-jenkins.canonical.com/artifacts/d7c57bfe-83e2-4583-a3cc-b66cdfa2a377/index.html

**Comment by sabaini** [comment]
So the timeout increase is merged and should be available on /edge in a few; lets see if this issue raises its ugly head again

**Comment by dvh312** [comment]
Thanks, just ran into this today as well.

**Comment by nakano57** [comment]
It always happens after rebooting, and I have to purge and install to fix it.

**Comment by sabaini** [comment]
I believe the orig. timeout issue should be fixed. See ticket #342 for issues on upgrading
