### ISSUE TITLE
ubuntu@canonical:~$ sudo microceph.ceph osd crush rule rm replicated_rule rule replicated_rule does not exist

### ISSUE THREAD

**Issue by KyleSanderson** [canonical/microceph#220]

**Comment by sabaini** [comment]
Hi @KyleSanderson ,

We recently made improvements for rule handling that have not landed in /stable yet, but would be available in the /candidate tracks. Would you be able to try the /candidate track?

Thanks.

**Comment by KyleSanderson** [comment]
Does it work? 😸 Projects go through this all the time, pinning the main branch to your release (if you're not aligning the docs to the released version) is one way around it. The other way is to version your docs until there's a stable version that's released.

**Comment by sabaini** [comment]
I believe it does! If you can, please give it a try and let us know

**Comment by UtkarshBhatthere** [comment]
@KyleSanderson I am marking this issue as closed. Please feel free to reopen it in case it's still erroneous.
