### ISSUE TITLE
Error: Failed adding new disk: Failed to open: Failed to luksOpen: /dev/disk/by-id/wwn-0x500605bc11c82fdd, exit status 2, Failed to load key in kernel keyring. No key available with this passphrase.

### ISSUE THREAD

**Issue by KyleSanderson** [canonical/microceph#221]
NOTE: OSD Encryption requires a snapd >= 2.59.1
Verify your version of snapd by running "snap version"

root@canonical:~# nap version^C
root@canonical:~# snap version
snap    2.60.3
snapd   2.60.3
series  16
ubuntu  22.04
kernel  6.1.0-1021-oem

**Comment by sabaini** [comment]
Hi @KyleSanderson ,

Do you have steps to reproduce this issue? Which microceph version did you use? Can you share some details around the environment, ideally via an sosreport? 

Thanks.

**Comment by KyleSanderson** [comment]
Literally step by step in the quick start. I did a quick search in the repo and found this response from someone else.

> Many thanks, I believe I could reproduce your results.
> 
> It appears that the seccomp assertions are not applied to running snap processes. Restarting the microceph.daemon process after connecting dm-crypt works around this issue. I have filed a case for snapd in bug #2034585 for this and will document the workaround in the MicroCeph docs as well, possibly will have to add a daemon restart in an interface hook

**Comment by sabaini** [comment]
As noted there users need to restart microceph.daemon after connecting the dm-crypt slot since the apparmor changes are not picked up for running processes. 

Does restarting microceph.daemon ie. `sudo snap connect microceph:dm-crypt ; sudo snap restart microceph.daemon` help solve the issue?

**Comment by UtkarshBhatthere** [comment]
Marking this issue as closed.
