### ISSUE TITLE
failed to set backend

### ISSUE THREAD

**Issue by sorinpepelea** [canonical/microceph#231]
this command :  `microceph.ceph orch set backend orchestrator`
gives Error EINVAL: Module 'orchestrator' is not enabled.
when I try `ceph mgr module enable orchestrator`
it says : module 'orchestrator' is already enabled (always-on)

With no orchestrator it cannot be enabled any nfs or rgw.
microceph version : 0.1
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
OS : Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-86-generic x86_64)

**Comment by sabaini** [comment]
Hi @sorinpepelea  we support RGW directly: `sudo microceph enable rgw`. There is no support for Orchestrator or NFS I'm afraid.
