### ISSUE TITLE
Are LVM volume groups supported?

### ISSUE THREAD

**Issue by iamwillbar** [canonical/microceph#254]
My homelab microk8s cluster is 3 x Intel NUCs that only have a single large (4 Tb) SSD. They have a single 100 Gb default `ubuntu-vg`, so there's plenty of space for an additional volume group. Can volume groups be used with microceph or does it need to be a dedicated physical disk?

**Comment by sabaini** [comment]
I'm afraid that this is unsupported at the moment, although we plan to address this gap

**Comment by ivoruetsche** [comment]
Well, we played around on Ubuntu 22.04 with this. Apparmor blocks this and we changed the responsible profiles. We let them run on the lab, but we never ever would roll it out on the prod sys as long this is not official supported, so it's your own risk.

Here how we did it on all cluster nodes, after the snap installation, but before we bootstraped the cluster:

In the directory /var/lib/snapd/apparmor/profiles/ you can find these files:
snap.microceph.microceph
snap.microceph.daemon
snap.microceph.osd

Find the section in that files with the allowed raw devices, called "# Access to raw devices, not individual partitions" and add your regex device as a line like:
`/dev/dm-[0-9] rwk,` or `/dev/sdb[0-9] rwk,`

Then, replace the old definition with the new definition:
```
apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.microceph.microceph
apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.microceph.daemon
apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.microceph.osd
```

But again, it's an unsupported hack and we have no idea about the impact!
Ivo

**Comment by ivoruetsche** [comment]
Another fancy approach was the loop device, because they are supported :-? - why ever...

- Format and mount the physical partition
- Create a raw image file like `dd if=/dev/zero of=/mnt/disk0p2/ceph_disk.img bs=1G count=100`
- `sudo losetup -f /mnt/disk0p2/ceph_disk.img`
- find the new loop device and use it as osd: `losetup | grep ceph_disk.img`

But, you have to add it after a reboot before the cluster starts... We didn't go deeper on that approach, but maybe give you an idea...

**Comment by sabaini** [comment]
Right, using a loop device would be a viaable alternative for a lab setup. 
Note that you need a recent-ish snapd for this, e.g. >2.60. For older snapd versions you can add a workaround like this

```
        loop_file="$(sudo mktemp -p /mnt XXXX.img)"
        sudo truncate -s 1G "${loop_file}"
        loop_dev="$(sudo losetup --show -f "${loop_file}")"
        minor="${loop_dev##/dev/loop}"
        sudo mknod -m 0660 "/dev/sdi21" b 7 "${minor}"
        sudo microceph disk add /dev/sdi21
```

With regard to hacking in additional apparmor rules: from a perspective of MicroCeph this works fine. The only caveat is that a snapd upgrade likely will overwrite the hacked-in rule so you'd need to hold snapd updates.

**Comment by Perovskikh** [comment]
> Подходит ли для microceph физический том, созданный с помощью LVM для выделенного диска?

Unfortunately, LVM does not work in microceph 1.29, but we are really waiting for the developers of microceph!
+-----------------------+---------+
|         PATH          | STATUS  |
+-----------------------+---------+
| /dev/mapper/vg0-lv--1 | Failure |
+-----------------------+---------+
Error:  failed to prepare data device: failed to wipe device /dev/mapper/vg0-lv--1: Failed to run: dd if=/dev/zero of=/dev/mapper/vg0-lv--1 bs=4M count=10 status=none: exit status 1 (dd: failed to open '/dev/mapper/vg0-lv--1': Permission denied)

**Comment by sabaini** [comment]
FTR this is being handled in https://github.com/snapcore/snapd/pull/13352
