### ISSUE TITLE
Feature Request: Ability to have Ceph using FDE

### ISSUE THREAD

**Issue by benoitjpnet** [canonical/microceph#265]
I am not a fan of not encrypting my data stored in Ceph.

Is this on the roadmap? Since MicroCeph already supports FDE, it could be implemented in MicroCloud when the cluster is bootstrapped.

Thank you very much!

**Comment by benoitjpnet** [comment]
My bad, wrong project...

**Comment by UtkarshBhatthere** [comment]
Using FDE directly from MicroCeph is straightforward itself. By using the `--encrypt` flag while disk addition you can instruct MicroCeph to do so. [Docs](https://canonical-microceph.readthedocs-hosted.com/en/latest/explanation/full-disk-encryption/)
