### ISSUE TITLE
Feature request CephFS

### ISSUE THREAD

**Issue by fzhan** [canonical/microceph#286]
# Issue report
There's not clear instructions nor documentation available for CephFS using microceph.

## What version of MicroCeph are you using ?
Reef

As CephFS as become available instruction for MicroCloud, an intergration between Microk8s & Microceph is missing the ceph file system module. It'd be great of a simple instruction of how-to, or build-in command can be available.

Thanks!

**Comment by fzhan** [comment]
After running 
```
ceph osd pool create cephfs_data
ceph osd pool create cephfs_metadata
ceph fs new cephfs cephfs_metadata cephfs_data
```
and
```
microk8s connect-external-ceph
```

picked up the new sc

That's a very simple instruction and could be included in the guide.

**Comment by UtkarshBhatthere** [comment]
Hello @fzhan, thanks for creating this issue.
microk8s uses rook-external-cluster to integrate with microceph backed ceph cluster and it works well. :)
So, I think the correct place to look for ceph consumption is [rook](https://rook.io/docs/rook/v1.12/CRDs/Cluster/external-cluster/#external-configuration) or [Ceph Docs](https://docs.ceph.com/en/quincy/cephfs/createfs/).
