### ISSUE TITLE
Failed adding new disk

### ISSUE THREAD

**Issue by anthonyra** [canonical/microceph#305]
# Issue report

With the latest version on Snap while `microcloud init` the microceph step crashes with the following error.

> Failed adding new disk: json: cannot unmarshal string into Go struct field DisksPost.path of type []string

## What version of MicroCeph are you using ?

ceph-version: 18.2.0-0ubuntu3~cloud0; microceph-git: 3f8909a69a
**channel:** reef/stable or latest/stable
**installed:** 18.2.0+snap3f8909a69a

## What are the steps to reproduce this issue ?

1. `sudo microcloud init`
2. setup everything selecting distributed storage (one for each member) and wipe disks
3. all local configurations complete (microcloud, lxd, microovn, microceph)
4. fails with above message when attempting to configure the other cluster members

## What happens (observed behaviour) ?
This crashes the init process requiring a complete rebuild of the leader but no configuration changes occur with the other members.

## What were you expecting to happen ?
Microceph should be able to stand up distributed storage.

## Relevant logs, error output, etc.
Not sure where to look for additional logs

## Additional comments.
Downgrading to Microceph version 0.1 removes this error

**Comment by UtkarshBhatthere** [comment]
Hey @anthonyra this is a bug caused by divergence of MicroCeph API, a compatibility patch is on the way and should fix the failure.

**Comment by anthonyra** [comment]
I'm not 100% sure but seems like a reasonable cause to what I'm seeing. If there's a way for me to test if it's indeed API divergence related let me know. I just don't get/have a lot of information into the this error. (I may also just don't know where to look to find the answer) but `microcloud` can't setup `microceph` when `microceph` is upgrade to the `reef/stable` channel.
