### ISSUE TITLE
Failed to add disk

### ISSUE THREAD

**Issue by Cirrus-8691** [canonical/microceph#317]
# Issue report

## What version of MicroCeph are you using ?
microceph (edge) 18.2.0+snapb959197794

Use this section to describe the channel/revision which produces the unexpected behaviour.
This information can be fetched from the `installed:` section of `sudo snap info microceph` output.

## What are the steps to reproduce this issue ?

1. Install last version of Ubuntu server 22 using VMWare player 17.0
2. swap to user root
3. root@microk8s-1:~# snap install microceph --channel=latest/edge
microceph (edge) 18.2.0+snapb959197794 from Canonical✓ installed

5. root@microk8s-1:~# microceph cluster bootstrap

7. root@microk8s-1:~# lsblk
sda      8:0    0    40G  0 disk 
├─sda1   8:1    0     1M  0 part 
└─sda2   8:2    0    40G  0 part /
sdb      8:16   0    20G  0 disk 

8. root@microk8s-1:~# microceph disk add /dev/sdb --wipe
+----------+---------+
|   PATH   | STATUS  |
+----------+---------+
| /dev/sdb | Failure |
+----------+---------+
Error: unable to list system disks: Failed to read "/proc/self/mountinfo": open /proc/self/mountinfo: permission denied

## Try to find disk with microceph:
root@microk8s-1:~# microceph disk list
Error: internal error: unable to fetch unpartitoned disks: internal error: unable to fetch available disks: failed listing storage devices: Failed to read "/proc/self/mountinfo": open /proc/self/mountinfo: permission denied

## Try to find and view "/proc/self/mountinfo" with root user: (no problem)

root@microk8s-1:~# ls -la /proc/self/mountinfo
-r--r--r-- 1 root root 0 Feb 27 13:10 /proc/self/mountinfo

root@microk8s-1:~# cat /proc/self/mountinfo
24 30 0:22 / /sys rw,nosuid,nodev,noexec,relatime shared:7 - sysfs sysfs rw
25 30 0:23 / /proc rw,nosuid,nodev,noexec,relatime shared:12 - proc proc rw
26 30 0:5 / /dev rw,nosuid,relatime shared:2 - devtmpfs udev rw,size=1926788k,nr_inodes=481697,mode=755,inode64
27 26 0:24 / /dev/pts rw,nosuid,noexec,relatime shared:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
28 30 0:25 / /run rw,nosuid,nodev,noexec,relatime shared:5 - tmpfs tmpfs rw,size=396952k,mode=755,inode64
30 1 8:2 / / rw,relatime shared:1 - ext4 /dev/sda2 rw
31 24 0:6 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:8 - securityfs securityfs rw
32 26 0:27 / /dev/shm rw,nosuid,nodev shared:4 - tmpfs tmpfs rw,inode64
33 28 0:28 / /run/lock rw,nosuid,nodev,noexec,relatime shared:6 - tmpfs tmpfs rw,size=5120k,inode64
34 24 0:29 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime shared:9 - cgroup2 cgroup2 rw,nsdelegate,memory_recursiveprot
35 24 0:30 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:10 - pstore pstore rw
36 24 0:31 / /sys/fs/bpf rw,nosuid,nodev,noexec,relatime shared:11 - bpf bpf rw,mode=700
37 25 0:32 / /proc/sys/fs/binfmt_misc rw,relatime shared:13 - autofs systemd-1 rw,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=29499
38 26 0:33 / /dev/hugepages rw,relatime shared:14 - hugetlbfs hugetlbfs rw,pagesize=2M
39 26 0:20 / /dev/mqueue rw,nosuid,nodev,noexec,relatime shared:15 - mqueue mqueue rw
40 24 0:7 / /sys/kernel/debug rw,nosuid,nodev,noexec,relatime shared:16 - debugfs debugfs rw
41 24 0:12 / /sys/kernel/tracing rw,nosuid,nodev,noexec,relatime shared:17 - tracefs tracefs rw
42 24 0:34 / /sys/fs/fuse/connections rw,nosuid,nodev,noexec,relatime shared:18 - fusectl fusectl rw
43 24 0:21 / /sys/kernel/config rw,nosuid,nodev,noexec,relatime shared:19 - configfs configfs rw
65 28 0:35 / /run/credentials/systemd-sysusers.service ro,nosuid,nodev,noexec,relatime shared:20 - ramfs none rw,mode=700
89 30 7:0 / /snap/lxd/24322 ro,nodev,relatime shared:30 - squashfs /dev/loop0 ro,errors=continue
92 30 7:2 / /snap/core20/2182 ro,nodev,relatime shared:45 - squashfs /dev/loop2 ro,errors=continue
95 30 7:1 / /snap/lxd/27037 ro,nodev,relatime shared:47 - squashfs /dev/loop1 ro,errors=continue
98 30 7:3 / /snap/core20/1974 ro,nodev,relatime shared:49 - squashfs /dev/loop3 ro,errors=continue
101 30 7:4 / /snap/snapd/19457 ro,nodev,relatime shared:51 - squashfs /dev/loop4 ro,errors=continue
104 30 7:5 / /snap/snapd/20671 ro,nodev,relatime shared:53 - squashfs /dev/loop5 ro,errors=continue
107 37 0:36 / /proc/sys/fs/binfmt_misc rw,nosuid,nodev,noexec,relatime shared:55 - binfmt_misc binfmt_misc rw
318 28 0:25 /snapd/ns /run/snapd/ns rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,size=396952k,mode=755,inode64
339 318 0:4 mnt:[4026532636] /run/snapd/ns/lxd.mnt rw - nsfs nsfs rw
344 28 0:46 / /run/user/1000 rw,nosuid,nodev,relatime shared:183 - tmpfs tmpfs rw,size=396948k,nr_inodes=99237,mode=700,uid=1000,gid=1000,inode64
367 30 7:6 / /snap/core22/1122 ro,nodev,relatime shared:192 - squashfs /dev/loop6 ro,errors=continue
694 30 7:7 / /snap/microceph/937 ro,nodev,relatime shared:290 - squashfs /dev/loop7 ro,errors=continue
1199 318 0:4 mnt:[4026532581] /run/snapd/ns/microceph.mnt rw - nsfs nsfs rw
root@microk8s-1:~# 

What did i do wrong ?

**Comment by sabaini** [comment]
Hey @Cirrus-8691 this is a snap confinement issue which is present on /edge -- hopefully we should have updated permissions soon, cf. https://forum.snapcraft.io/t/auto-connect-request-for-microceph-mount-observe/39030

Until this is fixed /stable should work better
