### ISSUE TITLE
Add support for LUKS encryption

### ISSUE THREAD

**Issue by stgraber** [canonical/microceph#34]
It would be great to have a story for encryption at rest.

Ideally, we'd want the ability to provide a single passphrase or key file to then unlock all the OSDs.
OSDs probably still ought to be individually encrypted with individual keys.

I'd suggest using one small LUKS volume that contains key files for each of the OSDs.
After system reboot, the user would need to do `microceph unlock` which would prompt for the passphrase (or key file) used to unlock that small LUKS volume. At that point, the OSD startup script will be able to read the keys for each of the OSDs from that volume and unlock them individually.

This makes it easy to change the key without having to alter each of the OSDs.

A `microceph lock` command could be added which would unmount and close the small LUKS volume.
Doing so would prevent any access to the individual OSD keys, which would in turn prevent the addition of additional OSDs but also prevent crashed OSD daemons from respawning (so a bit of a double edged sword).

**Comment by ChrisMacNaughton** [comment]
Rather the implementing bespoke encryption, we should consider and measure Ceph's built in OSD encryption options, and potentially enable it by default
