### ISSUE TITLE
permission denied error for disk add on an external usb hdd

### ISSUE THREAD

**Issue by saurabhkumar** [canonical/microceph#343]
# Issue report

## What version of MicroCeph are you using ?

snap-id:      ct1DgtIGBaljdOwomQGMLr8EJcL5pOP1
tracking:     latest/edge
refresh-date: yesterday at 21:48 CEST
hold:         forever
channels:
  reef/stable:      18.2.0+snap450240f5dd 2024-04-09 (979) 78MB -
  reef/candidate:   18.2.0+snap71f71782c5 2024-04-22 (982) 78MB -
  reef/beta:        ↑
  reef/edge:        18.2.0+snap71f71782c5 2024-04-08 (982) 78MB -
  latest/stable:    18.2.0+snap450240f5dd 2024-04-09 (979) 78MB -
  latest/candidate: 18.2.0+snap71f71782c5 2024-04-22 (982) 78MB -
  latest/beta:      ↑
  latest/edge:      18.2.0+snap71f71782c5 2024-04-08 (982) 78MB -
  quincy/stable:    0+git.4a608fc         2024-01-10 (795) 86MB -
  quincy/candidate: 0+git.4a608fc         2023-11-30 (795) 86MB -
  quincy/beta:      ↑
  quincy/edge:      0+git.287ee68         2023-12-05 (809) 86MB -
installed:          18.2.0+snap71f71782c5            (982) 78MB held

## What are the steps to reproduce this issue ?
I installed microceph for experimentation on a raspberry pi cluster with 3 nodes and each node having an external usb hard disk (NTFS). After adding the nodes, issuing ` sudo microceph cluster list` shows that the nodes are online.

On one of the nodes, ` lsblk | grep -v loop` shows the following:

sda           8:0    0 465.8G  0 disk
└─sda1        8:1    0 465.8G  0 part /mnt/drive1
mmcblk0     179:0    0 119.1G  0 disk
├─mmcblk0p1 179:1    0   512M  0 part /boot/firmware
└─mmcblk0p2 179:2    0 118.6G  0 part /snap
                                      /
I modified permission using `sudo chmod 777 /mnt/drive1`
(the disk is usable and the fstab file has also been modified to mount it at startup and this works)

## What happens (observed behaviour) ?
The command `sudo microceph disk add /dev/sda1 --wipe` gives the following error:

+-----------+---------+
|   PATH    | STATUS  |
+-----------+---------+
| /dev/sda1 | Failure |
+-----------+---------+
Error: failed to prepare data device: failed to wipe device /dev/disk/by-id/wwn-0x3020221222205440-part1: Failed to run: dd if=/dev/zero of=/dev/disk/by-id/wwn-0x3020221222205440-part1 bs=4M count=10 status=none: exit status 1 (dd: failed to open '/dev/disk/by-id/wwn-0x3020221222205440-part1': Permission denied)

## What were you expecting to happen ?
The disk should get added.

**Comment by UtkarshBhatthere** [comment]
FWIR, at the moment, MicroCeph does not support enrolling partitioned disks as OSDs. You can however, create loop back block devices with backing files kept in the external drive and then enroll the loop devices as OSDs.

**Comment by saurabhkumar** [comment]
Thank you for the info.
