### ISSUE TITLE
docs: TYPE YOUR QUESTION HERE

### ISSUE THREAD

**Issue by brkcnbz** [canonical/microceph#347]
*Please describe the question or issue you're facing with "MicroCeph documentation".*

I couldn't fully understand the licensing part; wouldn't using a self-hosted S3 service behind a paid ERP program pose a problem for us in terms of AGPL v3?

---
*Reported from: https://canonical-microceph.readthedocs-hosted.com/en/reef-stable/*

**Comment by sabaini** [comment]
I am not a lawyer (and this is not legal advice), but from my understanding this is not necessarily a problem. You would need to provide source for any changes to MicroCeph itself (if you made any). If the ERP program merely used MicroCeph, e.g. as a storage backend, this would not mean you would have to distribute the ERP program. It does depend on your specific use case and I'd advise to contact your legal team for a definitive answer.
