### ISSUE TITLE
microceph disk list ignores listing disks less than 2GB

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/microceph#348]
# Issue report

## What version of MicroCeph are you using ?

reef/stable

## What are the steps to reproduce this issue ?

Follow tutorial https://canonical-microceph.readthedocs-hosted.com/en/latest/tutorial/single-node/
Ensure the disk size is less than 2GB

## What happens (observed behaviour) ?

microceph disk list --> does not print disks that are less than 2GB
microceph add-osd does not seem to have such restriction

## What were you expecting to happen ?
Disks that are less than 2GB should not be SILENTLY ignored as the information will be missing by the tools using microceph command and an additional overhead on the tools to check device size.

## Additional comments.
[1] https://github.com/canonical/microceph/blob/450240f5dd0d24853354a5a3306a5bd85b429c9a/microceph/cmd/microceph/disk_list.go#L183

**Comment by UtkarshBhatthere** [comment]
As discussed, the threshold has been set to filter out unsuitable storage devices from the `disk list` command output. We don't use this filter on `disk add` cmd so if one tries to add a disk smaller than 2GiB, it will be successfully added. However, one may argue that an OSD this small is not suitable for Ceph.
