### ISSUE TITLE
[Feature Request] Possibility to add for Microk8s prior to 1.28

### ISSUE THREAD

**Issue by fzhan** [canonical/microceph#354]
# Issue report

## What version of MicroCeph are you using ?
ceph-version: 18.2.0-0ubuntu3~cloud0; microceph-git: 71f71782c5
microk8s 1.26

**Comment by UtkarshBhatthere** [comment]
I am sorry the issue is not detailed enough to act upon. Please take a moment to describe it more. 

I am marking the issue closed, feel free to re-open it once you have added some more details.

**Comment by fzhan** [comment]
@UtkarshBhatthere apologies for the briefty. I'm not sure if that'd be a feature request or an issue.

We are currently using microk8s 1.26 due to other restrictions on the infrastructure but want to utilise the versatality of this package, during feasibility testing we can't seem to find any support document for enabling microceph for older version of microk8s. Would you please kindly share your insight on this?

Thanks.

**Comment by fzhan** [comment]
@UtkarshBhatthere thank you, I will explore in the MicroK8s repo / config section.
