### ISSUE TITLE
Enhancement: Ability to set keystone related configs in rgw

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/microceph#360]
# Enhancement

rgw service in microceph currently do not set any configs related to keystone integration.
Enhance microceph to be able to set these params using microceph cli. 

Reference configs - [1]
[1] https://docs.ceph.com/en/latest/radosgw/keystone/

**Comment by UtkarshBhatthere** [comment]
To support this in MicroCeph, these configs would be added in the `microceph cluster config` support list.
This would require:
1. Addition of the desired config values in the config table
2. RGW handles for the node-wise daemon restart
