### ISSUE TITLE
Deadlock in upgrade process

### ISSUE THREAD

**Issue by sabaini** [canonical/microceph#386]
# Issue report

When upgrading a multinode cluster we typically want to iterate over all nodes sequentially so as to keep the cluster available.

With the recent changes in microcluster, the microcephd now waits for all daemons to be on the same version before starting up. 

However, ceph daemons (mon, osd etc.) wait for the microcephd to update ceph.conf after an upgrade (fixing up `run dir` e.g.)

Thus we have a deadlock: upgrade can only continue with the next node after the current node is completely up, but this can't complete until all nodes are on the same version.

We'll need to decouple microcephd from the ceph daemons for the upgrade process, e.g. by having a separate post-upgrade hook that updates the ceph.conf run dir.

## What version of MicroCeph are you using ?

latest/edge, rev 1071

**Comment by UtkarshBhatthere** [comment]
The post-upgrade hook suggestion seems legit to me. +1
