### ISSUE TITLE
Deletion of cluster member does not update mon.host in ceph.conf

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/microceph#396]
# Issue report

## What version of MicroCeph are you using ?

reef/edge:        18.2.0+snap0863c8b720     2024-07-31 (1108) 87MB -

## What are the steps to reproduce this issue ?

1. Follow [microceph multi-node tutorial] and deploy 3 node microceph. lets say node names are micro1, micro2, micro3
2. Remove micro2 from the cluster
    sudo mciroceph cluster remove micro2 
    
## What happens (observed behaviour) ?

Verify `/var/snap/microceph/current/conf/ceph.conf` on rest of the 2 nodes
`mon host` has all 3 node IPs

## What were you expecting to happen ?

Expected `mon host` should have only micro1 and micro3 IPs

## Additional comments.

Charm microceph has function `get_mon_public_addresses` which gets monitor IPs from `/var/snap/microceph/current/conf/ceph.conf` on leader unit. Charm microceph provides
clients faulty mon public addresses until this issue is fixed.

**Comment by UtkarshBhatthere** [comment]
Fix in a PR commit: https://github.com/canonical/microceph/pull/374/commits/6a3475a3599f6884463ffee8673ca817d91366a0
