### ISSUE TITLE
Error: failed listing disks: Database is still starting

### ISSUE THREAD

**Issue by DerKnerd** [canonical/microceph#423]
# Issue report

## What version of MicroCeph are you using ?

reef/stable

## What are the steps to reproduce this issue ?

I am not sure how to reproduce

## What happens (observed behaviour) ?

After rebooting my three microceph servers all of them hang at the error stated above. This is all I get when I execute `microceph status`

## What were you expecting to happen ?

Microceph starting up

## Relevant logs, error output, etc.

This is the only log I get

https://gist.github.com/DerKnerd/e5b2b3ee0aeb020e3d3182b118ae8509

## Additional comments.

This just happend out of random after the three servers rebooted and I never had any issues before that.

**Comment by DerKnerd** [comment]
One thing I must note, the ceph.conf lists servers that don't exist anymore and they don't get replaced. Up until now that didn't cause any issues. But maybe I need to replace the servers in the database? How do I do that if it is indeed the issue?

**Comment by DerKnerd** [comment]
Ok, I found the issue and it had nothing to do with microceph. I changed something on my VPN server and that caused the issues. After reverting that change everything worked again.

**Comment by UtkarshBhatthere** [comment]
@DerKnerd can you share what configurations on your VPN caused the issue ? This will be helpful for any future traveller.

**Comment by DerKnerd** [comment]
Sure, I enabled the firewall without having the correct ports open, so yeah, an embarissing rookie mistake that happend to a veteran :smile:
