### ISSUE TITLE
Microceph cluster join fails with "Last error: Joining server certificate SAN does not contain join token name"

### ISSUE THREAD

**Issue by asbalderson** [canonical/microceph#471]
# Issue report

## What version of MicroCeph are you using ?
squid/stable:     19.2.0+snap9aeaeb2970 2024-11-13 (1228) 

## What are the steps to reproduce this issue ?

1. on machine 1: snap install microceph; snap connect microceph:hardware-observe
2. on machine 2: snap install microceph; snap connect microceph:hardware-observe
3. on machine 1: microceph cluster bootstrap
4. on machine 1: microceph cluster add <machine 2>
5. on machine 2: microceph cluster join <token>

## What happens (observed behavior) ?
The cluster join command returned:
Error: 1 join attempts were unsuccessful. Last error: Joining server certificate SAN does not contain join token name

## What were you expecting to happen ?
Expected for machine 2 to join the ceph cluster with machine 1.

## Relevant logs, error output, etc.

machine 1 logs: (cat syslog | grep microceph)
https://gist.github.com/asbalderson/34a0da580911e2e71ba3d27a59693fe1
machine 2 logs:
https://gist.github.com/asbalderson/c2edc09379d91c6da7b88b85a255955e
If it’s considerably long, please paste to https://gist.github.com/ and insert the link here.

**Comment by sabaini** [comment]
Hey :-) 
As discussed in elsewhere the problem is due to microcluster (which is being used in MicroCeph) is now actually checking host names for security, so the host you use to generate the token with `microceph cluster add X` must match the actual hostname X of the node where the `microceph cluster join` is being run

**Comment by asbalderson** [comment]
thanks for fixing a bug we were using as a feature :)
we can close this and ill fix the issues on our end
