### ISSUE TITLE
RFE: non-interactive `microceph init` 

### ISSUE THREAD

**Issue by sabaini** [canonical/microceph#57]
For automation it would be desirable to have a method of initializing a cluster non-interactively, e.g. by supplying all necessary info as cli args to `microceph init`

**Comment by stgraber** [comment]
`microceph init` is effectively just a wrapper around:
 - microceph cluster bootstrap
 - microceph cluster join
 - microceph disk add

So for testing you probably ought to use those instead.

**Comment by sabaini** [comment]
Thanks, fair enough. I still think having a version of `microceph init` which pre-fills one or more values would be good UI but it's probably not high prio
